---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.6
- name: centos-5.11

suites:
- name: default
  data_bag_path: "test/integration/default/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
  run_list: ["recipe[certificate::manage_by_attributes]"]
  attributes:
    certificate: [
      test: {
        data_bag_type: 'encrypted',
        nginx_cert: true,
        cert_file: "test.pem",
        key_file: "test.key"
      }
    ]
- name: unencrypted
  data_bag_path: "test/integration/unencrypted/data_bags"
  run_list: ["recipe[certificate::manage_by_attributes]"]
  attributes:
    certificate: [
      test: {
        data_bag_type: 'unencrypted',
        nginx_cert: true,
        cert_file: "test.pem",
        key_file: "test.key"
      }
    ]
- name: custom
  run_list: ["recipe[certificate::custom_by_attributes]"]
  attributes:
    certificate: 
      cert_file: 'custom_test.pem'
      key_file: 'custom_test.key'
      chain_file: 'custom_test_bundle.crt'
      cert_file_source: '-----BEGIN CERTIFICATE-----\ncertificate\n-----END CERTIFICATE-----'
      key_file_source: '-----BEGIN KEY-----\nkey\n-----END KEY-----'
      chain_file_source: '-----BEGIN CERTIFICATE-----\nca_certificate\n-----END CERTIFICATE-----'

