Encoding:
  Enabled: false
LineLength:
  Max: 200
HashSyntax:
  Enabled: false
Style/RescueModifier:
  Enabled: false
RedundantSelf:
  Exclude:
    - 'recipes/manage_by_attributes.rb'
AllCops:
  Exclude:
  - '.kitchen/*'
  - 'providers/manage.rb'
