Encoding:
  Enabled: False
LineLength:
  Max: 200
HashSyntax:
  Enabled: False
Style/RescueModifier:
  Enabled: false
AllCops:
  Exclude:
  - '.kitchen/*'
Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
